version: "3.9"

services:
  alfredo:
    container_name: alfredo
    image: juanfu26/alfredo
    build:
      context: ../
    env_file: .env
    ports:
      - 8080:80
    volumes:
      - ../app:/code/app
      - ../data:/data
      - ../persist:/persist
