version: "3.9"

services:
  alfredo:
    container_name: alfredo
    image: juanfu26/alfredo
    build: 
      context: ../
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    ports: 
      - 8080:80
    volumes:
      - ../app:/code/app
      - ../data:/data
